/**
 * Sweden's 290 municipalities and 21 counties, in their correct spelling.
 *
 * Used to repair free-text searches typed without å/ä/ö. A list is the only
 * honest way to do this: a rule that simply maximises diacritics turns
 * "norrkoping" into "nörrköping", because it has no way to know that the first
 * o is right and the second is wrong.
 */

export const SWEDISH_PLACES: readonly string[] = [
  // Blekinge
  'Karlshamn',
  'Karlskrona',
  'Olofström',
  'Ronneby',
  'Sölvesborg',
  // Dalarna
  'Avesta',
  'Borlänge',
  'Falun',
  'Gagnef',
  'Hedemora',
  'Leksand',
  'Ludvika',
  'Malung-Sälen',
  'Mora',
  'Orsa',
  'Rättvik',
  'Smedjebacken',
  'Säter',
  'Vansbro',
  'Älvdalen',
  // Gotland
  'Gotland',
  'Visby',
  // Gävleborg
  'Bollnäs',
  'Gävle',
  'Hofors',
  'Hudiksvall',
  'Ljusdal',
  'Nordanstig',
  'Ockelbo',
  'Ovanåker',
  'Sandviken',
  'Söderhamn',
  // Halland
  'Falkenberg',
  'Halmstad',
  'Hylte',
  'Kungsbacka',
  'Laholm',
  'Varberg',
  // Jämtland
  'Berg',
  'Bräcke',
  'Härjedalen',
  'Krokom',
  'Ragunda',
  'Strömsund',
  'Åre',
  'Östersund',
  // Jönköping
  'Aneby',
  'Eksjö',
  'Gislaved',
  'Gnosjö',
  'Habo',
  'Jönköping',
  'Mullsjö',
  'Nässjö',
  'Sävsjö',
  'Tranås',
  'Vaggeryd',
  'Vetlanda',
  'Värnamo',
  // Kalmar
  'Borgholm',
  'Emmaboda',
  'Hultsfred',
  'Högsby',
  'Kalmar',
  'Mönsterås',
  'Mörbylånga',
  'Nybro',
  'Oskarshamn',
  'Torsås',
  'Vimmerby',
  'Västervik',
  // Kronoberg
  'Alvesta',
  'Lessebo',
  'Ljungby',
  'Markaryd',
  'Tingsryd',
  'Uppvidinge',
  'Växjö',
  'Älmhult',
  // Norrbotten
  'Arjeplog',
  'Arvidsjaur',
  'Boden',
  'Gällivare',
  'Haparanda',
  'Jokkmokk',
  'Kalix',
  'Kiruna',
  'Luleå',
  'Pajala',
  'Piteå',
  'Älvsbyn',
  'Överkalix',
  'Övertorneå',
  // Skåne
  'Bjuv',
  'Bromölla',
  'Burlöv',
  'Båstad',
  'Eslöv',
  'Helsingborg',
  'Hässleholm',
  'Höganäs',
  'Hörby',
  'Höör',
  'Klippan',
  'Kristianstad',
  'Kävlinge',
  'Landskrona',
  'Lomma',
  'Lund',
  'Malmö',
  'Osby',
  'Perstorp',
  'Simrishamn',
  'Sjöbo',
  'Skurup',
  'Staffanstorp',
  'Svalöv',
  'Svedala',
  'Tomelilla',
  'Trelleborg',
  'Vellinge',
  'Ystad',
  'Åstorp',
  'Ängelholm',
  'Örkelljunga',
  'Östra Göinge',
  // Stockholm
  'Botkyrka',
  'Danderyd',
  'Ekerö',
  'Haninge',
  'Huddinge',
  'Järfälla',
  'Lidingö',
  'Nacka',
  'Norrtälje',
  'Nykvarn',
  'Nynäshamn',
  'Salem',
  'Sigtuna',
  'Sollentuna',
  'Solna',
  'Stockholm',
  'Sundbyberg',
  'Södertälje',
  'Tyresö',
  'Täby',
  'Upplands-Bro',
  'Upplands Väsby',
  'Vallentuna',
  'Vaxholm',
  'Värmdö',
  'Österåker',
  // Södermanland
  'Eskilstuna',
  'Flen',
  'Gnesta',
  'Katrineholm',
  'Nyköping',
  'Oxelösund',
  'Strängnäs',
  'Trosa',
  'Vingåker',
  // Uppsala
  'Enköping',
  'Heby',
  'Håbo',
  'Knivsta',
  'Tierp',
  'Uppsala',
  'Älvkarleby',
  'Östhammar',
  // Värmland
  'Arvika',
  'Eda',
  'Filipstad',
  'Forshaga',
  'Grums',
  'Hagfors',
  'Hammarö',
  'Karlstad',
  'Kil',
  'Kristinehamn',
  'Munkfors',
  'Storfors',
  'Sunne',
  'Säffle',
  'Torsby',
  'Årjäng',
  // Västerbotten
  'Bjurholm',
  'Dorotea',
  'Lycksele',
  'Malå',
  'Nordmaling',
  'Norsjö',
  'Robertsfors',
  'Skellefteå',
  'Sorsele',
  'Storuman',
  'Umeå',
  'Vilhelmina',
  'Vindeln',
  'Vännäs',
  'Åsele',
  // Västernorrland
  'Härnösand',
  'Kramfors',
  'Sollefteå',
  'Sundsvall',
  'Timrå',
  'Ånge',
  'Örnsköldsvik',
  // Västmanland
  'Arboga',
  'Fagersta',
  'Hallstahammar',
  'Kungsör',
  'Köping',
  'Norberg',
  'Sala',
  'Skinnskatteberg',
  'Surahammar',
  'Västerås',
  // Västra Götaland
  'Ale',
  'Alingsås',
  'Bengtsfors',
  'Bollebygd',
  'Borås',
  'Dals-Ed',
  'Essunga',
  'Falköping',
  'Färgelanda',
  'Grästorp',
  'Gullspång',
  'Göteborg',
  'Götene',
  'Herrljunga',
  'Hjo',
  'Härryda',
  'Karlsborg',
  'Kungälv',
  'Lerum',
  'Lidköping',
  'Lilla Edet',
  'Lysekil',
  'Mariestad',
  'Mark',
  'Mellerud',
  'Munkedal',
  'Mölndal',
  'Orust',
  'Partille',
  'Skara',
  'Skövde',
  'Sotenäs',
  'Stenungsund',
  'Strömstad',
  'Svenljunga',
  'Tanum',
  'Tibro',
  'Tidaholm',
  'Tjörn',
  'Tranemo',
  'Trollhättan',
  'Töreboda',
  'Uddevalla',
  'Ulricehamn',
  'Vara',
  'Vårgårda',
  'Vänersborg',
  'Åmål',
  'Öckerö',
  // Örebro
  'Askersund',
  'Degerfors',
  'Hallsberg',
  'Hällefors',
  'Karlskoga',
  'Kumla',
  'Laxå',
  'Lekeberg',
  'Lindesberg',
  'Ljusnarsberg',
  'Nora',
  'Örebro',
  // Östergötland
  'Boxholm',
  'Finspång',
  'Kinda',
  'Linköping',
  'Mjölby',
  'Motala',
  'Norrköping',
  'Söderköping',
  'Vadstena',
  'Valdemarsvik',
  'Ydre',
  'Åtvidaberg',
  'Ödeshög',
  // Counties, as people type them
  'Blekinge',
  'Dalarna',
  'Gävleborg',
  'Halland',
  'Jämtland',
  'Jönköpings län',
  'Kalmar län',
  'Kronoberg',
  'Norrbotten',
  'Skåne',
  'Södermanland',
  'Uppland',
  'Värmland',
  'Västerbotten',
  'Västernorrland',
  'Västmanland',
  'Västra Götaland',
  'Östergötland',
];
